# Generated by Django 3.2.8 on 2021-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('uuid', models.IntegerField()),
                ('plate_number', models.CharField(max_length=120, null=True)),
                ('group', models.CharField(max_length=120, null=True)),
                ('date', models.CharField(max_length=120)),
                ('direction', models.CharField(max_length=120, null=True)),
                ('status', models.IntegerField()),
                ('type_passage', models.IntegerField()),
                ('photo', models.CharField(max_length=120, null=True)),
                ('ssync', models.BooleanField(null=True)),
            ],
        ),
    ]
